version: '3.7'

services:
  nginx:
    image: nginx:1.14.2-alpine
    volumes:
      - ./php-mysql-image/html:/usr/share/nginx/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php
      - mysql
  scraper:
    build: ./nodejs-scraper
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SCAN_RANGE: ${SCAN_RANGE}
      SCAN_INTERVAL: ${SCAN_INTERVAL}
    network_mode: host
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        MYSQL_ALLOW_EMPTY_PASSWORD: 0
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    build: ./php-mysql-image
    ports:
      - "9000"
    volumes:
      - ./php-mysql-image/html:/usr/share/nginx/html
    depends_on:
      - mysql
